(()=>{
  const D=window.PROMPTER_DATA;if(!D)return;
  const slug=s=>s.toLowerCase().normalize('NFD').replace(/[\u0300-\u036f]/g,'').replace(/[^a-z0-9]+/g,'_').replace(/^_|_$/g,'');
  const promptFor=(n,k)=>({style:`${n.toLowerCase()} influence`,instrument:n.toLowerCase(),vocal:`${n.toLowerCase()} vocal technique`,prod:`${n.toLowerCase()} sound`,harmony:`${n.toLowerCase()} harmonic language`,rhythm:`${n.toLowerCase()} rhythmic feel`}[k]||n.toLowerCase());
  const add=(id,label,section,names,kind='instrument',priority=5)=>{
    if(D.categories.some(c=>c.id===id))return;
    const options=[{id:'none',label:'Keine Vorgabe',prompt:'',priority:0},...names.split('|').map(n=>({id:slug(n),label:n,prompt:promptFor(n,kind),priority}))];
    D.categories.push({id,label,section,options});
  };

  add('sceneStylesMega','Stile / Szenen Mega','Stil & Richtung',`Post-Punk|Goth Rock|Deathrock|Batcave|Darkwave|Coldwave|Minimal Wave|New Wave|No Wave|Noise Rock|Math Rock|Post-Rock|Slowcore|Sadcore|Emo|Midwest Emo|Screamo|Post-Hardcore|Hardcore Punk|Crust Punk|D-Beat|Garage Punk|Garage Rock|Psychedelic Rock|Acid Rock|Krautrock|Space Rock|Stoner Rock|Desert Rock|Sludge Metal|Post-Metal|Doom Metal|Funeral Doom|Drone Metal|Black Metal|Atmospheric Black Metal|Depressive Black Metal|Blackgaze|Doomgaze|Death Metal|Melodic Death Metal|Technical Death Metal|Progressive Death Metal|Death-Doom|Gothic Metal|Symphonic Metal|Power Metal|Folk Metal|Viking Metal|Industrial Metal|Nu Metal|Rap Metal|Groove Metal|Thrash Metal|Speed Metal|Djent|Mathcore|Metalcore|Melodic Metalcore|Alternative Metal|Progressive Metal|Heavy Psych|Shoegaze|Dream Pop|Ethereal Wave|Neo-Psychedelia|Jangle Pop|Indie Rock|Indie Pop|Art Rock|Art Pop|Chamber Pop|Baroque Pop|Power Pop|Britpop|Madchester|Baggy|Sophisti-Pop|City Pop|Shibuya-kei|Visual Kei|Anisong|J-Pop|K-Pop|Hyperpop|Digicore|Glitch Pop|Electropop|Synthpop|Future Pop|Industrial Pop|Trip-Hop|Downtempo|Chillout|Lounge|Acid Jazz|Nu Jazz|Jazz Fusion|Bebop|Hard Bop|Modal Jazz|Cool Jazz|Free Jazz|Spiritual Jazz|Big Band|Swing|Ragtime|Stride Piano|Delta Blues|Chicago Blues|Electric Blues|Swamp Blues|Hill Country Blues|Gospel Blues|Soul Blues|Neo-Soul|Quiet Storm|Motown|Northern Soul|Philly Soul|Deep Soul|Southern Soul|P-Funk|Boogie|Disco|Italo Disco|Euro Disco|Nu-Disco|French House|Chicago House|Garage House|Deep House|Tech House|Minimal House|Microhouse|Progressive House|Afro House|Soulful House|Acid House|Detroit Techno|Dub Techno|Minimal Techno|Hard Techno|Industrial Techno|Schranz|Acid Techno|Melodic Techno|Electro|Electroclash|EBM|Dark Electro|Future Garage|2-Step Garage|UK Bassline|Grime|Dubstep|Brostep|Riddim|Jungle|Drum and Bass|Liquid DnB|Neurofunk|Techstep|Breakbeat|Big Beat|Breakcore|IDM|Glitch|Glitch Hop|Footwork|Juke|Jersey Club|Baltimore Club|Baile Funk|Phonk|Memphis Rap|G-Funk|Boom Bap|Jazz Rap|Conscious Rap|Abstract Hip-Hop|Cloud Rap|Drill|Trap|Lo-Fi Hip-Hop|Alternative R&B|Contemporary R&B|New Jack Swing|Dub|Roots Reggae|Rocksteady|Ska|Dancehall|Reggaeton|Dembow|Cumbia|Salsa|Bachata|Merengue|Tango|Flamenco|Fado|Chanson|Cabaret|Klezmer|Polka|Balkan Brass|Bluegrass|Old-Time|Americana|Dark Americana|Outlaw Country|Honky-Tonk|Country Rock|Western|Zydeco|Cajun|Afrobeat|Afrobeats|Amapiano|Gqom|Highlife|Soukous|Gnawa|Rai|Qawwali|Bhangra|Bollywood|Hindustani Classical|Carnatic Classical|Gamelan|Dangdut|Future Funk|Vaporwave|Mallsoft|Witch House|Hauntology|Berlin School|Drone Ambient|Dark Ambient|Space Ambient|New Age|Psytrance|Goa Trance|Progressive Trance|Hardstyle|Gabber|Speedcore|Chiptune|Dungeon Synth|Neo-Classical|Minimal Classical|Contemporary Classical|Electroacoustic|Musique Concrete|Experimental|Avant-Garde`, 'style',8);

  add('regionalStylesMega','Regionen / Traditionen Mega','Stil & Richtung',`Nordic Folk|Celtic Folk|Irish Traditional|Scottish Traditional|Welsh Folk|Breton Folk|Balkan Folk|Greek Folk|Turkish Folk|Anatolian Rock|Persian Classical|Arabic Classical|Levantine Folk|Maghreb Folk|Gnawa|Andalusian Classical|Sephardic|Klezmer|Romani Music|Flamenco|Fado|Galician Folk|Basque Folk|Appalachian|Cajun|Zydeco|Tejano|Mariachi|Ranchera|Norteno|Son Jarocho|Cuban Son|Bolero|Mambo|Cha-Cha-Cha|Salsa|Bachata|Merengue|Cumbia|Vallenato|Andean Folk|Nueva Cancion|Samba|Bossa Nova|Forro|Baiao|Maracatu|Tropicália|Afrobeat|Highlife|Soukous|Makossa|Mbalax|Gnawa|Ethio-Jazz|Taarab|Amapiano|Gqom|Maskandi|Qawwali|Ghazal|Bhangra|Hindustani|Carnatic|Baul|Nepali Folk|Tibetan Chant|Mongolian Traditional|Tuvan Throat Singing|Chinese Traditional|Jiangnan Sizhu|Peking Opera|Japanese Gagaku|Shakuhachi Honkyoku|Enka|Okinawan Folk|Korean Gugak|Pansori|Indonesian Gamelan|Balinese Gamelan|Javanese Gamelan|Dangdut|Thai Luk Thung|Vietnamese Traditional|Filipino Kundiman|Polynesian Traditional|Maori Traditional|Australian Aboriginal`, 'style',6);

  add('guitarMega','Gitarren Mega','Instrumente',`Classical Nylon Guitar|Steel String Acoustic Guitar|Parlor Guitar|Jumbo Acoustic Guitar|12-String Acoustic Guitar|Resonator Guitar|Dobro|National Steel Guitar|Lap Steel Guitar|Pedal Steel Guitar|Baritone Guitar|Bass VI|Hollowbody Jazz Guitar|Semi-Hollow Guitar|Telecaster Twang|Stratocaster Clean|Humbucker Rock Guitar|P90 Guitar|Surf Guitar|Shoegaze Guitar Wall|E-Bow Guitar|Bowed Electric Guitar|Prepared Guitar|Feedback Guitar|Palm-Muted Guitar|Tremolo-Picked Guitar|Fingerpicked Guitar|Slide Guitar|Open-Tuning Acoustic Guitar|Fuzz Guitar|Octave Fuzz Guitar|Chorus Clean Guitar|Rotary Guitar|Reverse Guitar|Delay-Dotted Guitar|Ambient Swell Guitar|Math-Rock Tapping Guitar|Djent Low-Tuned Guitar|7-String Guitar|8-String Guitar|Nashville-Tuned Guitar|Requinto Guitar|Tres Guitar|Portuguese Guitar|Gypsy Jazz Guitar|Flamenco Guitar`, 'instrument',5);

  add('stringsMega','Streicher / Zupfer Mega','Instrumente',`Solo Violin|Fiddle|Baroque Violin|Electric Violin|Viola|Solo Cello|Electric Cello|Bowed Double Bass|String Quartet|String Quintet|Chamber Strings|Large String Section|Pizzicato Strings|Tremolo Strings|Sul Ponticello Strings|Sul Tasto Strings|Col Legno Strings|String Harmonics|Glissando Strings|Portamento Strings|Hardanger Fiddle|Nyckelharpa|Erhu|Gaohu|Morin Khuur|Sarangi|Esraj|Rebab|Kamancheh|Lyra|Harp|Celtic Harp|Lever Harp|Mandolin|Octave Mandolin|Mandola|Banjo|Ukulele|Bouzouki|Oud|Saz|Baglama|Lute|Theorbo|Koto|Shamisen|Sitar|Sarod|Tanpura|Veena|Pipa|Ruan|Guzheng|Qanun|Cimbalom|Hammered Dulcimer|Balalaika|Domra|Charango|Cuatro|Ronroco|Kora|Ngoni|Guembri`, 'instrument',5);

  add('keysMega','Piano / Keys Mega','Instrumente',`Concert Grand Piano|Felt Piano|Upright Piano|Detuned Upright Piano|Honky-Tonk Piano|Prepared Piano|Tack Piano|Toy Piano|Rhodes Electric Piano|Wurlitzer Electric Piano|Hohner Pianet|Clavinet|Hammond B3 Organ|Pipe Organ|Reed Organ|Harmonium|Celesta|Harpsichord|Clavichord|Melodica|Accordion|Concertina|Bandoneon|Farfisa Organ|Vox Continental Organ|Mellotron Strings|Mellotron Choir|Mellotron Flute|DX7 Electric Piano|FM Bell Keys|Analog Poly Keys|House Piano|Rave Piano|Gospel Organ|Church Organ|Pump Organ|Player Piano`, 'instrument',5);

  add('windsMega','Holzbläser / Flöten Mega','Instrumente',`Concert Flute|Piccolo|Alto Flute|Bass Flute|Recorder|Bass Recorder|Pan Flute|Ney|Shakuhachi|Dizi|Xiao|Bansuri|Ocarina|Quena|Tin Whistle|Irish Low Whistle|Native American Flute|Fujara|Oboe|English Horn|Oboe d Amore|Bassoon|Contrabassoon|Clarinet|Bass Clarinet|Contrabass Clarinet|Soprano Saxophone|Alto Saxophone|Tenor Saxophone|Baritone Saxophone|Bass Saxophone|Harmonica|Bass Harmonica|Chromatic Harmonica|Sheng|Suona|Zurna|Duduk|Bagpipes|Uilleann Pipes|Gaida|Hulusi|Shehnai|Hichiriki|Launeddas`, 'instrument',5);

  add('brassMega','Blechbläser Mega','Instrumente',`Trumpet|Muted Trumpet|Piccolo Trumpet|Flugelhorn|Cornet|Trombone|Bass Trombone|French Horn|Wagner Tuba|Euphonium|Baritone Horn|Tuba|Sousaphone|Cimbasso|Alphorn|Natural Horn|Brass Quartet|Brass Quintet|Large Brass Section|Horn Ensemble|Trumpet Choir|Trombone Choir`, 'instrument',5);

  add('percussionMega','Percussion Mega','Instrumente',`Timpani|Concert Bass Drum|Orchestral Snare|Field Drum|Tambourine|Shaker|Maracas|Cabasa|Guiro|Claves|Cowbell|Agogo Bells|Congas|Bongos|Timbales|Cajon|Djembe|Talking Drum|Udu|Frame Drum|Bodhran|Tabla|Mridangam|Dhol|Dholak|Taiko|Tombak|Darbuka|Riq|Qraqeb|Gamelan Gong|Bonang|Gender Metallophone|Steelpan|Kalimba|Mbira|Marimba|Vibraphone|Xylophone|Glockenspiel|Tubular Bells|Hand Bells|Temple Blocks|Wood Blocks|Castanets|Claves|Finger Cymbals|Crotales|Tam-Tam|Suspended Gong|Singing Bowls|Crystal Bowls|Waterphone|Flexatone|Rainstick|Ocean Drum|Log Drum|Slit Drum|Tongue Drum|Handpan|Hang Drum|Berimbau|Shekere|Caxixi|Pandeiro|Surdo|Cuica|Repinique|Ganza|Claves Afro-Cuban|Bata Drums|Ashiko|Bougarabou|Kpanlogo Drums`, 'instrument',5);

  add('bassMega','Bass Mega','Instrumente',`Upright Bass|Bowed Double Bass|Fretless Bass|Fingerstyle Electric Bass|Picked Electric Bass|Slap Bass|Muted Bass Guitar|Fuzz Bass|Distorted Bass|Octave Bass|Bass VI|Short-Scale Bass|Hofner-Style Bass|Rickenbacker-Style Bass|Dub Bass|Reggae Bass|Motown Bass|Funk Bass|Moog Bass|Mono Analog Bass|FM Bass|Reese Bass|Acid 303 Bass|Pure Sub Bass|Sine Sub Bass|808 Bass|Gliding 808 Bass|Short 808 Bass|Log Drum Bass|Wobble Bass|Neuro Bass|Growl Bass|Donk Bass|Reverse Bass`, 'instrument',5);

  add('drumsMega','Drums / Maschinen Mega','Instrumente',`Brush Drum Kit|Mallet Drum Kit|Dry Studio Kit|Roomy Live Kit|Vintage 60s Kit|Fat 70s Kit|Gated 80s Kit|Indie Rock Kit|Arena Rock Kit|Metal Kit|Jazz Kit|Soul Kit|Funk Kit|Motown Kit|Boom Bap Kit|Trap Kit|Drill Kit|Jungle Breaks|Amen Break|Think Break|Funky Drummer Break|Half-Time Drums|Double-Time Drums|Double-Kick Drums|Blast Beats|D-Beat|Motorik Drums|Tribal Toms|Military Snare|Marching Drums|TR-808|TR-909|TR-606|TR-707|TR-727|CR-78|LinnDrum|DMX Drum Machine|Simmons Drums|MPC-Style Drums|SP-1200-Style Drums|12-Bit Drum Sampler|Lo-Fi Drum Machine`, 'instrument',5);

  add('synthMega','Synths Mega','Instrumente',`Minimoog Lead|Moog Modular|Prophet Pad|Juno Pad|Juno Bass|Oberheim Pad|CS-80 Lead|ARP Odyssey|ARP 2600|SH-101 Bass|TB-303 Acid Line|DX7 Keys|DX7 Bass|FM Bell|FM Pad|Wavetable Synth|Granular Synth|Additive Synth|Physical Modeling Synth|Modular Analog Synth|Eurorack Texture|Analog Step Sequencer|Berlin School Sequencer|Dark Supersaw|Soft Supersaw|Square Lead|Sine Lead|Triangle Lead|Pulse Lead|Synth Pluck|Digital Pluck|Air Pad|Dark Pad|Warm Analog Pad|Choir Pad|Formant Pad|Drone Synth|Noise Synth|Resonant Noise Sweep|Vocoder Pad|Talkbox Synth|Theremin|Ondes Martenot|Mellotron|String Machine|Solina Strings|Fairlight-Style Sample Texture|Synclavier-Style Digital Tone|PPG-Style Wavetable|Vaporwave Pad|Cyberpunk Bass|Industrial Synth Stab|Rave Hoover|Acid Resonance|Chiptune Pulse|8-Bit Lead|16-Bit Game Synth`, 'instrument',5);

  add('rareMega','Seltene Instrumente Mega','Instrumente',`Glass Harmonica|Glass Harp|Musical Saw|Hurdy-Gurdy|Autoharp|Hammered Dulcimer|Appalachian Dulcimer|Jaw Harp|Didgeridoo|Handpan|Steel Tongue Drum|Lithophone|Waterphone|Flexatone|Ocean Harp|Aeolian Harp|Theremin|Ondes Martenot|Trautonium|Cristal Baschet|Chapman Stick|Warr Guitar|Hang Drum|Hang Gongs|Singing Bowls|Crystal Bowls|Church Bells|Carillon|Tubular Bells|Typewriter Percussion|Found Metal|Chains Percussion|Stone Percussion|Wood Percussion|Brake Drum|Anvil|Oil Drum|Metal Pipe Percussion|Hydrophone Texture|Water Droplets|Ice Cracks|Bowls and Glasses|Music Box|Toy Glockenspiel|Toy Piano|Stylophone|Otamatone-Like Tone|Circuit-Bent Toy|Prepared Guitar|Prepared Bass|Prepared Piano`, 'instrument',4);

  add('vocalMega','Vocaltechniken Mega','Stimme & Gesang',`Straight Tone|Slow Vibrato|Fast Vibrato|Wide Vibrato|Controlled Belting|Head Voice|Falsetto|Breathy Falsetto|Chest Voice|Mixed Voice|Vocal Fry|Subtle Rasp|Grit|Cry Tone|Sobbing Breaks|Audible Breaths|Legato|Staccato|Melisma|Runs and Riffs|Half-Spoken Half-Sung|Chant|Call and Response|Unison Stack|Double-Tracked Lead|Octave Double|Three-Part Harmony|Four-Part Harmony|Five-Part Harmony|Close Harmony|Open Harmony|Gospel Runs|Soul Runs|Yodel|Kulning|Overtone Singing|Throat Singing|Khoomei|Sygyt|Kargyraa|Vocoder Vocal|Talkbox Vocal|Telephone Vocal|Megaphone Vocal|Distorted Vocal Layer|Reverse Vocal Texture|Wordless Humming|Wordless Ahh|Wordless Mhhh|Vocal Drone|Breath Choir`, 'vocal',7);

  add('harmonyMega','Harmonie Mega','Rhythmus & Energie',`Natural Minor|Harmonic Minor|Melodic Minor|Dorian|Phrygian|Phrygian Dominant|Lydian|Mixolydian|Locrian|Pentatonic|Minor Pentatonic|Blues Scale|Whole-Tone Scale|Octatonic Scale|Chromatic Harmony|Atonal Harmony|Bitonal Harmony|Polytonal Harmony|Quartal Harmony|Quintal Harmony|Tone Clusters|Drone Harmony|Pedal Tone|Suspension-Rich Harmony|Add9 Chords|Major 7 Chords|Minor 7 Chords|Minor-Major 7|Dominant 7|Jazz Extensions|Neo-Soul Chords|Modal Interchange|Chromatic Mediants|Parallel Chords|Open Fifths|Power Chords|Dissonant Seconds|Tritone Tension|Twelve-Tone Row|Microtonal Harmony`, 'harmony',6);

  add('rhythmMega','Rhythmus / Takt Mega','Rhythmus & Energie',`Straight 4/4|Waltz 3/4|Flowing 6/8|Fast 6/8|5/4|5/8|7/4|7/8|9/8|10/8|11/8|12/8|13/8|15/8|Mixed Meter|Changing Meter|Polymeter|Polyrhythm|Free Time|Rubato|Swing|Shuffle|Half-Time|Double-Time|Four-on-the-Floor|Motorik|Tresillo|Dembow|Son Clave|Rumba Clave|Bossa Pulse|Samba Pulse|Afro-Cuban 6/8|Broken Beat|Syncopated Groove|Behind the Beat|Ahead of the Beat|Push-Pull Timing|Ghost-Note Groove|Minimal Pulse|Galloping Rhythm|Triplet Feel|Dotted Rhythm|Hemiola|Euclidean Rhythm|Additive Rhythm`, 'rhythm',6);

  add('productionMega','Produktion / Effekte Mega','Produktion & Sound',`Spring Reverb|Plate Reverb|Chamber Reverb|Small Room Reverb|Large Hall Reverb|Cathedral Reverb|Gated Reverb|Reverse Reverb|Convolution Reverb|Tape Echo|Slapback Delay|Dub Delay|Ping-Pong Delay|Dotted Delay|Multi-Tap Delay|Analog Chorus|Dimension Chorus|Flanger|Phaser|Rotary Speaker|Tremolo Effect|Vibrato Effect|Auto-Pan|Ring Modulation|Bitcrush|Downsample|Granular Fragmentation|Spectral Freeze|Tape Stop|Vinyl Stop|Wow and Flutter|Tape Saturation|Tube Saturation|Console Saturation|Parallel Distortion|Overdrive|Fuzz Processing|Lo-Fi Filtering|Telephone Filter|AM Radio Filter|Band-Pass Filter|Low-Pass Movement|High-Pass Movement|Sidechain Pumping|Parallel Compression|Bus Compression|Transient Shaping|Soft Transients|Hard Transients|Mono Mix|Narrow Stereo|Wide Stereo|Binaural Space|Mid-Side Width|Close-Mic Dry|Room-Mic Heavy|One-Take Live|Cassette Recording|Reel-to-Reel Tape|12-Bit Sampler|16-Bit Sampler|SP-1200 Grain|MPC Swing|Vinyl Noise|Tape Hiss|Electrical Hum|Field Recording|Foley Texture|Industrial Room Tone|Rain Texture|Wind Texture|Ocean Texture|Fire Crackle|City Ambience|Train Ambience|Reverse Texture|Spectral Smear|Sub Drops|Cinematic Impacts|Textural Risers|No Mastering Polish|High Dynamic Range|Dark Top End|Airy Top End|Mid-Forward Mix|Sub-Heavy Mix|Vocal-Forward Mix|Drum-Forward Mix|Bass-Forward Mix`, 'prod',4);
})();